Add Ledger support
project-serum/spl-token-wallet pull request #23
Opened 2020-10-18 18:49 UTC by bartosz-lipinski

Changes:
1. Added support logout
2. Add separate way to auth using ledger
3. Add WalletProvider interface that supports localStorage and ledger
4. Enable HTTPS for local development
5. 

TODO: 
- [ ] Error handling
- [ ] Large transaction signing
- [ ] Expose non-root ledger accounts
- [ ] Code refactor (move ledger logic to single folder)

UX preview: 
![image](https://user-images.githubusercontent.com/264380/96377044-55384280-1148-11eb-9be3-af36b2f37734.png)

2020-10-19 17:29 UTC, bartosz-lipinski commented
For SPL transactions we will need migrate to new format (transfer2, approve2, mintTo2). Solana ledger app doesn't recognized old format and requires user to enable 'blind sign'. I will submit separate PR for that.

2020-10-20 02:54 UTC, nishadsingh1 commented
Awesome! Thanks for putting this together

Will review in the coming days

2020-10-30 10:01 UTC, sconybeare requested changes
Can you split the refactoring and the ledger support changes into separate PRs? Currently it's difficult to review the changes for correctness.

2020-10-30 14:34 UTC, bartosz-lipinski commented
> Can you split the refactoring and the ledger support changes into separate PRs? Currently it's difficult to review the changes for correctness.

@sconybeare not sure what you mean by refactoring changes everything in this PR was need to get ledger up and running.

2020-11-09 07:52 UTC, nathanielparke reviewed
Left a few comments, but mostly looks good.

2020-11-09 07:52 UTC, nathanielparke commented on src/pages/LoginPage.js
> +            <Button type="secondary" style={{ cursor: 'pointer', marginLeft: 'auto', marginRight: 0, textTransform: 'none', fontWeight: 'normal' }}
can we run prettier to correct indents here?

2020-11-09 07:52 UTC, nathanielparke commented on src/components/NavigationFrame.js
> +          onClick={() => {
this should be 
```
onClick={() => {
  setAnchorEl(null);
  logout();
}}
```

null is un-necessary for the logout function, and setting the dropdown state to null when we logout fixes the dropdown rendering opened in a weird place when we log back in

2021-02-22 04:58 UTC, closed without merging